-- =============================================================================
-- USER SERVICE SQL QUERIES
-- Database: auth_db (user-service)
-- Table: "user"
-- =============================================================================

-- =============================================================================
-- TABLE STRUCTURE
-- =============================================================================

-- Note: This is auto-generated by Prisma, but shown here for reference
CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    password_hash TEXT,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    profile_image_url TEXT,
    role VARCHAR(50) NOT NULL DEFAULT 'buyer',
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    email_verified BOOLEAN NOT NULL DEFAULT false,
    phone_verified BOOLEAN NOT NULL DEFAULT false,
    last_login_at TIMESTAMPTZ(6),
    last_login_ip VARCHAR(45),
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ(6)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_email ON "user"(email);
CREATE INDEX IF NOT EXISTS idx_user_phone_number ON "user"(phone_number);
CREATE INDEX IF NOT EXISTS idx_user_role ON "user"(role);
CREATE INDEX IF NOT EXISTS idx_user_status ON "user"(status);
CREATE INDEX IF NOT EXISTS idx_user_deleted_at ON "user"(deleted_at);

-- =============================================================================
-- SELECT QUERIES (READ OPERATIONS)
-- =============================================================================

-- 1. Get user by ID
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    profile_image_url,
    role,
    status,
    email_verified,
    phone_verified,
    last_login_at,
    created_at,
    updated_at
FROM "user"
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL;

-- 2. Get user by email
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    role,
    status,
    email_verified,
    phone_verified
FROM "user"
WHERE email = 'user@example.com'
  AND deleted_at IS NULL;

-- 3. Get user by phone number
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    role,
    status,
    phone_verified
FROM "user"
WHERE phone_number = '+6281234567890'
  AND deleted_at IS NULL;

-- 4. Get user with password hash (for authentication)
SELECT
    id,
    email,
    phone_number,
    password_hash,
    role,
    status,
    failed_attempts,
    locked_until
FROM "user"
WHERE phone_number = '+6281234567890'
  AND deleted_at IS NULL;

-- 5. List all active users (paginated)
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    role,
    status,
    created_at
FROM "user"
WHERE deleted_at IS NULL
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 20 OFFSET 0;

-- 6. Search users by name or email
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    role,
    status
FROM "user"
WHERE deleted_at IS NULL
  AND (
    first_name ILIKE '%search_term%'
    OR last_name ILIKE '%search_term%'
    OR email ILIKE '%search_term%'
  )
ORDER BY created_at DESC
LIMIT 20;

-- 7. Get users by role
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    status,
    created_at
FROM "user"
WHERE role = 'seller'
  AND deleted_at IS NULL
ORDER BY created_at DESC;

-- 8. Get recently registered users (last 7 days)
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    role,
    created_at
FROM "user"
WHERE created_at >= NOW() - INTERVAL '7 days'
  AND deleted_at IS NULL
ORDER BY created_at DESC;

-- 9. Get users with unverified email
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    created_at
FROM "user"
WHERE email_verified = false
  AND email IS NOT NULL
  AND deleted_at IS NULL
ORDER BY created_at DESC;

-- 10. Get users with unverified phone
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    created_at
FROM "user"
WHERE phone_verified = false
  AND deleted_at IS NULL
ORDER BY created_at DESC;

-- 11. Get locked users (failed login attempts)
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    failed_attempts,
    locked_until,
    last_login_at
FROM "user"
WHERE locked_until > NOW()
  AND deleted_at IS NULL
ORDER BY locked_until DESC;

-- 12. Count users by role
SELECT
    role,
    COUNT(*) as user_count
FROM "user"
WHERE deleted_at IS NULL
GROUP BY role
ORDER BY user_count DESC;

-- 13. Count users by status
SELECT
    status,
    COUNT(*) as user_count
FROM "user"
WHERE deleted_at IS NULL
GROUP BY status
ORDER BY user_count DESC;

-- 14. Get user registration stats (daily for last 30 days)
SELECT
    DATE(created_at) as registration_date,
    COUNT(*) as new_users
FROM "user"
WHERE created_at >= NOW() - INTERVAL '30 days'
  AND deleted_at IS NULL
GROUP BY DATE(created_at)
ORDER BY registration_date DESC;

-- =============================================================================
-- INSERT QUERIES (CREATE OPERATIONS)
-- =============================================================================

-- 15. Create new user (basic registration with phone)
INSERT INTO "user" (
    phone_number,
    password_hash,
    first_name,
    last_name,
    role,
    status,
    phone_verified
)
VALUES (
    '+6281234567890',
    '$2b$10$hashedPasswordHere',
    'John',
    'Doe',
    'buyer',
    'active',
    false
)
RETURNING id, phone_number, first_name, last_name, role, created_at;

-- 16. Create new user with email
INSERT INTO "user" (
    email,
    phone_number,
    password_hash,
    first_name,
    last_name,
    role,
    status,
    email_verified,
    phone_verified
)
VALUES (
    'john.doe@example.com',
    '+6281234567890',
    '$2b$10$hashedPasswordHere',
    'John',
    'Doe',
    'buyer',
    'pending_verification',
    false,
    false
)
RETURNING id, email, phone_number, first_name, last_name, role, created_at;

-- 17. Create seller user
INSERT INTO "user" (
    email,
    phone_number,
    password_hash,
    first_name,
    last_name,
    role,
    status,
    phone_verified
)
VALUES (
    'seller@example.com',
    '+6281234567890',
    '$2b$10$hashedPasswordHere',
    'Jane',
    'Smith',
    'seller',
    'active',
    true
)
RETURNING id, email, phone_number, first_name, last_name, role, created_at;

-- =============================================================================
-- UPDATE QUERIES (UPDATE OPERATIONS)
-- =============================================================================

-- 18. Update user profile
UPDATE "user"
SET
    first_name = 'Updated First Name',
    last_name = 'Updated Last Name',
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, first_name, last_name, updated_at;

-- 19. Update user email
UPDATE "user"
SET
    email = 'newemail@example.com',
    email_verified = false,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, email, email_verified, updated_at;

-- 20. Update user phone number
UPDATE "user"
SET
    phone_number = '+6289876543210',
    phone_verified = false,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, phone_number, phone_verified, updated_at;

-- 21. Verify email
UPDATE "user"
SET
    email_verified = true,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, email, email_verified, updated_at;

-- 22. Verify phone
UPDATE "user"
SET
    phone_verified = true,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, phone_number, phone_verified, updated_at;

-- 23. Update password
UPDATE "user"
SET
    password_hash = '$2b$10$newHashedPasswordHere',
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, updated_at;

-- 24. Update profile image
UPDATE "user"
SET
    profile_image_url = 'https://cdn.lakoo.id/users/profile-pic.jpg',
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, profile_image_url, updated_at;

-- 25. Update user role (e.g., buyer to seller)
UPDATE "user"
SET
    role = 'seller',
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, role, updated_at;

-- 26. Update user status
UPDATE "user"
SET
    status = 'suspended',
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, status, updated_at;

-- 27. Record successful login
UPDATE "user"
SET
    last_login_at = NOW(),
    last_login_ip = '192.168.1.100',
    failed_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, last_login_at, last_login_ip;

-- 28. Increment failed login attempts
UPDATE "user"
SET
    failed_attempts = failed_attempts + 1,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, failed_attempts;

-- 29. Lock user account (after max failed attempts)
UPDATE "user"
SET
    locked_until = NOW() + INTERVAL '30 minutes',
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, locked_until;

-- 30. Unlock user account
UPDATE "user"
SET
    failed_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, failed_attempts, locked_until;

-- =============================================================================
-- DELETE QUERIES (SOFT DELETE)
-- =============================================================================

-- 31. Soft delete user (set deleted_at)
UPDATE "user"
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NULL
RETURNING id, deleted_at;

-- 32. Restore soft-deleted user
UPDATE "user"
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = 'USER_ID_HERE'
  AND deleted_at IS NOT NULL
RETURNING id, deleted_at;

-- 33. Hard delete user (DANGEROUS - permanent deletion)
-- Only use in development or with proper authorization
DELETE FROM "user"
WHERE id = 'USER_ID_HERE';

-- 34. Delete inactive users (not logged in for 2 years, soft delete)
UPDATE "user"
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE last_login_at < NOW() - INTERVAL '2 years'
  AND status = 'inactive'
  AND deleted_at IS NULL
RETURNING id, email, phone_number, last_login_at;

-- =============================================================================
-- COMPLEX QUERIES (JOINS & ANALYTICS)
-- =============================================================================

-- 35. Get user with active sessions
SELECT
    u.id,
    u.email,
    u.phone_number,
    u.first_name,
    u.last_name,
    u.last_login_at,
    COUNT(s.id) as active_sessions
FROM "user" u
LEFT JOIN user_session s ON u.id = s.user_id
    AND s.is_active = true
    AND s.expires_at > NOW()
WHERE u.id = 'USER_ID_HERE'
  AND u.deleted_at IS NULL
GROUP BY u.id;

-- 36. Get user with session history
SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    s.device_type,
    s.browser,
    s.os,
    s.ip_address,
    s.last_active_at,
    s.created_at as session_created_at
FROM "user" u
LEFT JOIN user_session s ON u.id = s.user_id
WHERE u.id = 'USER_ID_HERE'
  AND u.deleted_at IS NULL
ORDER BY s.created_at DESC
LIMIT 10;

-- 37. Get users who have never logged in
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    created_at
FROM "user"
WHERE last_login_at IS NULL
  AND deleted_at IS NULL
  AND created_at < NOW() - INTERVAL '7 days'
ORDER BY created_at DESC;

-- 38. Get user engagement stats
SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    u.created_at,
    u.last_login_at,
    COUNT(DISTINCT s.id) as total_sessions,
    MAX(s.last_active_at) as last_active
FROM "user" u
LEFT JOIN user_session s ON u.id = s.user_id
WHERE u.deleted_at IS NULL
GROUP BY u.id
ORDER BY last_active DESC NULLS LAST
LIMIT 100;

-- 39. Get users with pending OTP verification
SELECT
    u.id,
    u.email,
    u.phone_number,
    u.first_name,
    u.last_name,
    o.type as otp_type,
    o.created_at as otp_created_at,
    o.expires_at as otp_expires_at
FROM "user" u
INNER JOIN otp_verification o ON u.id = o.user_id
WHERE o.is_used = false
  AND o.expires_at > NOW()
  AND u.deleted_at IS NULL
ORDER BY o.created_at DESC;

-- 40. Get user audit trail
SELECT
    u.id,
    u.email,
    u.phone_number,
    a.action,
    a.ip_address,
    a.success,
    a.fail_reason,
    a.created_at as action_timestamp
FROM "user" u
LEFT JOIN auth_audit_log a ON u.id = a.user_id
WHERE u.id = 'USER_ID_HERE'
  AND u.deleted_at IS NULL
ORDER BY a.created_at DESC
LIMIT 50;

-- =============================================================================
-- ADMIN QUERIES
-- =============================================================================

-- 41. Get all admin users
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    role,
    status,
    created_at
FROM "user"
WHERE role IN ('admin', 'super_admin')
  AND deleted_at IS NULL
ORDER BY created_at DESC;

-- 42. Get suspended/banned users
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    status,
    updated_at
FROM "user"
WHERE status IN ('suspended', 'banned')
  AND deleted_at IS NULL
ORDER BY updated_at DESC;

-- 43. Get users pending verification
SELECT
    id,
    email,
    phone_number,
    first_name,
    last_name,
    email_verified,
    phone_verified,
    created_at
FROM "user"
WHERE status = 'pending_verification'
  AND deleted_at IS NULL
ORDER BY created_at DESC;

-- 44. Check if email exists (for registration validation)
SELECT EXISTS(
    SELECT 1
    FROM "user"
    WHERE email = 'test@example.com'
      AND deleted_at IS NULL
) as email_exists;

-- 45. Check if phone exists (for registration validation)
SELECT EXISTS(
    SELECT 1
    FROM "user"
    WHERE phone_number = '+6281234567890'
      AND deleted_at IS NULL
) as phone_exists;

-- =============================================================================
-- PERFORMANCE & MAINTENANCE
-- =============================================================================

-- 46. Analyze table for query optimization
ANALYZE "user";

-- 47. Get table statistics
SELECT
    schemaname,
    tablename,
    n_live_tup as live_rows,
    n_dead_tup as dead_rows,
    last_vacuum,
    last_autovacuum,
    last_analyze,
    last_autoanalyze
FROM pg_stat_user_tables
WHERE tablename = 'user';

-- 48. Check index usage
SELECT
    indexname,
    idx_scan as index_scans,
    idx_tup_read as tuples_read,
    idx_tup_fetch as tuples_fetched
FROM pg_stat_user_indexes
WHERE tablename = 'user'
ORDER BY idx_scan DESC;

-- =============================================================================
-- NOTES
-- =============================================================================

/*
IMPORTANT SECURITY NOTES:
1. Never expose password_hash in SELECT queries (except for authentication)
2. Always check deleted_at IS NULL to exclude soft-deleted users
3. Use parameterized queries to prevent SQL injection
4. Hash passwords with bcrypt before storing (never store plain text)
5. Implement rate limiting on login attempts
6. Use HTTPS for all user data transmission

PERFORMANCE TIPS:
1. Use indexes on frequently queried columns (email, phone_number, role, status)
2. Use LIMIT and OFFSET for pagination
3. Avoid SELECT * in production (specify columns)
4. Use EXPLAIN ANALYZE to optimize slow queries
5. Consider partitioning for very large user tables

SOFT DELETE PATTERN:
- Always check deleted_at IS NULL in WHERE clauses
- Use deleted_at = NOW() instead of DELETE for soft delete
- Set deleted_at = NULL to restore soft-deleted records
*/
